### ISSUE TITLE
waves size less than 256 and more than 512 failed

### ISSUE THREAD

**Issue by ArieLeo** [speps/GX-EncinoWaves#1]
Hi, sorry for creating an issue on your old repo.
i find an error when trying to set the waves FFT size to less than 255 or more than 512 it produce an error at line 260, the SetTexture was failed to assign the texture into the compute shader.

**Comment by speps** [comment]
This is because you need to change `EncinoFFT.compute` at the top to add the new sizes. It's quite easy, copy/paste and change the values accordingly.

I added 1024 support in 7f8ddeb as an example.
